name: Deploy
on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - run: mkdir ~/.ssh
    - run: 'echo "$SSH_KEY" >> ~/.ssh/devops'
    - run: chmod 400 ~/.ssh/devops
    - run: ssh-keyscan -t rsa  54.185.222.144  >> ~/.ssh/known_hosts
    - run: scp -i ~/.ssh/devops -r ./build/ devops@54.185.222.144:/var/www/html/
