name: Deploy
on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - name: Copy files to server
      uses: appleboy/scp-action@master              
      with:
        host: ${{ secrets.SSH_HOST }}
        username: new_user
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./build/"
        target: "/home/new_user/"
    - name: Host Files 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: new_user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: cp -r /home/new_user/build/*  /var/www/html/
