name: Deploy
on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - run: mkdir ~/.ssh
    - run: 'echo "$SSH_KEY" >> ~/.ssh/prabin'
    - run: chmod 400 ~/.ssh/prabin
    - run: echo -e "Host 54.185.222.144\n\tUser prabin\n\tHostname 54.185.222.144\n\tIdentityFile ~/.ssh/prabin\n\tStrictHostKeyChecking No" >> ~/.ssh/config
    - run: rsync -avz ssh ./build 54.185.222.144:~/
